default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV["POSTGRES_PASSWORD"] %> # Ensure you set this environment variable
  host: localhost  # or your database host (e.g., a Railway-provided hostname)
  port: 5432       # default PostgreSQL port
  timeout: 5000

development:
  <<: *default
#  url: <%#= ENV["DATABASE_URL"] %>
  url: postgresql://postgres:password@localhost:5432/user_crud_development
#  database: user_crud_development
#  username: <%#= ENV['USER_NAME'] %>
#  password: <%#= ENV["USER_PASSWORD"] %>

test:
  <<: *default
  database: user_crud_test

production:
  <<: *default
#  database: user_crud_production
#  username: 'postgres'
#  password: 'password'
#  password: <%#= ENV["USER_CRUD_DATABASE_PASSWORD"] %>
#  host: <%#= ENV["PRODUCTION_DB_HOST"] %>  # If using an external PostgreSQL host
  url: <%= ENV["DATABASE_URL"] %>
